spring.application.name=dresses
spring.datasource.url=jdbc:postgresql://localhost:5432/dress_shop
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud_name=dvluotbgi
cloudinary.api_key=869775248241215
cloudinary.api_secret=vX1TxZRZ0nQ6E3Nxs6GchRZFYNk

